### ISSUE TITLE
Step1 missing "babel-runtime" package

### ISSUE THREAD

**Issue by lbcsy** [strongloop/loopback-getting-started#36]
Check out tag "step1", after running "npm i", run "node ." failed with error: 

```
module.js:545
    throw err;
    ^

Error: Cannot find module 'babel-runtime/helpers/extends'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.module.exports.Object.defineProperty.value (/Users/bochenlin/dev/loopback/loopback-getting-started/node_modules/swagger-client/dist/index.js:1:777)
    at t (/Users/bochenlin/dev/loopback/loopback-getting-started/node_modules/swagger-client/dist/index.js:1:177)
    at Object.<anonymous> (/Users/bochenlin/dev/loopback/loopback-getting-started/node_modules/swagger-client/dist/index.js:1:16367)
    at t (/Users/bochenlin/dev/loopback/loopback-getting-started/node_modules/swagger-client/dist/index.js:1:177)
    at Object.module.exports.Object.defineProperty.value (/Users/bochenlin/dev/loopback/loopback-getting-started/node_modules/swagger-client/dist/index.js:1:15912)
    at t (/Users/bochenlin/dev/loopback/loopback-getting-started/node_modules/swagger-client/dist/index.js:1:177)
    at /Users/bochenlin/dev/loopback/loopback-getting-started/node_modules/swagger-client/dist/index.js:1:534
    at Object.<anonymous> (/Users/bochenlin/dev/loopback/loopback-getting-started/node_modules/swagger-client/dist/index.js:1:544)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
```

**Comment by dhmlau** [comment]
@lbcsy , I've tried to reproduce your issue but failed. Here is what I've done:
```
$ git clone https://github.com/strongloop/loopback-getting-started.git
$ git fetch --all --tags --prune
$ git checkout tags/step1
$ npm i
$ node . 
```

I got the following output with no errors:
```
Web server listening at: http://localhost:3000
Browse your REST API at http://localhost:3000/explorer
```

**Comment by dhmlau** [comment]
@lbcsy , are you still encountering this problem?

**Comment by dhmlau** [comment]
Closing due to inactivity. @lbcsy , if you still encounter this problem, please ping me here.  Thanks.
