### ISSUE TITLE
Getting Started throwing eventemiiter2 error

### ISSUE THREAD

**Issue by GeoffreyEmery** [strongloop/loopback-getting-started#4]
Hello I run this app on windows box and get the error from below. I have other version of this running so I believe the system is set up properly. 
I also re-installed the evenemitter just in case

'''

C:\dev\source\strongloop\loopback-getting-started\loopback-getting-started>node .

module.js:340
    throw err;
          ^
Error: Cannot find module 'eventemitter2'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\dev\source\strongloop\loopback-getting-started\loopback-getting-started\node_modules\loopback\node_modules\strong-remoting\lib\remote-o
bjects.js:11:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
'''

**Comment by superkhau** [comment]
Can you provide a link to a test project on Github? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by GeoffreyEmery** [comment]
This is working must have been a late night eyes
